# Generated by Django 3.0.7 on 2020-07-02 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200701_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자 목록'},
        ),
        migrations.CreateModel(
            name='FollowRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(choices=[('f', 'follow'), ('b', 'block')], default='f', max_length=1)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('from_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', related_query_name='follower_relation', to=settings.AUTH_USER_MODEL)),
                ('to_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', related_query_name='following_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_user_following_+', through='members.FollowRelations', to=settings.AUTH_USER_MODEL),
        ),
    ]
