# Generated by Django 3.0.7 on 2020-07-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200702_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followrelations',
            options={'verbose_name': '팔로우', 'verbose_name_plural': '팔로우 목록'},
        ),
        migrations.AlterField(
            model_name='followrelations',
            name='related_type',
            field=models.CharField(choices=[('f', 'Follow'), ('b', 'Block')], default='f', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='followrelations',
            unique_together={('from_relation', 'to_relation')},
        ),
    ]
