# Generated by Django 3.0.7 on 2020-07-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200702_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrelations',
            old_name='related_type',
            new_name='relation_type',
        ),
    ]
